server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone : http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #服务注册到eureka集群地址

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FourFiveEggs/springcloud-config.git #Github上git仓库名称
          search-paths :
            - springcloud-config #搜索目录
          default-label: master #读取分支
