server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    #url: jdbc:mysql://10.211.55.5:3306/db2019?useUnicode=true&characterEncoding-utr-8&useSSL=false #mbp数据库地址
    url: jdbc:mysql://127.0.0.1:3306/db2019?useUnicode=true&characterEncoding-utr-8&useSSL=false #window 数据库连接地址
    username: root
    password: root
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities       #所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: paymnet8001
    prefer-ip-address: true #访问地址可以显示IP地址
#    lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务器发送心跳的时间间隔，单位为秒（默认30秒）
#    lease-expiration-duration-in-seconds: 2 #Eureka服务段端在收到最后一次心跳后等待时间上限，单位为秒（默认90秒），超时将剔除服务
